---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-backstage-app-2
  description: Some description of the sample-backstage-app-2 component
spec:
  type: website
  lifecycle: production
  owner: group:team1
  system: sample-backstage-system
  dependsOn:
    - resource:default/sample-backstage-app-1
  consumesApis:
    - sample-backstage-app-2-api